# Generated by Django 3.2.15 on 2025-11-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jianying_draft_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='剪映草稿路径'),
        ),
    ]
