# Generated by Django 3.2.15 on 2026-02-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_jianying_draft_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
