# Generated by Django 3.2.15 on 2026-03-11 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_add_image_type_to_globalvariable'),
        ('projects', '0004_series_and_project_episode_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssetBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bindings', to='prompts.globalvariable', verbose_name='资产')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_bindings', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目资产绑定',
                'verbose_name_plural': '项目资产绑定',
                'db_table': 'project_asset_bindings',
                'ordering': ['created_at'],
                'unique_together': {('project', 'asset')},
            },
        ),
        migrations.AddIndex(
            model_name='projectassetbinding',
            index=models.Index(fields=['project', 'created_at'], name='project_asse_project_5d0d77_idx'),
        ),
    ]
