# Generated by Django 5.1.2 on 2026-03-12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_episode_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', '草稿'),
                    ('queued', '等待中'),
                    ('processing', '处理中'),
                    ('completed', '已完成'),
                    ('failed', '失败'),
                    ('paused', '已暂停'),
                ],
                default='draft',
                max_length=20,
                verbose_name='状态',
            ),
        ),
        migrations.CreateModel(
            name='EpisodeTaskQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('pipeline', '完整流程'), ('stage', '单阶段')], default='pipeline', max_length=20, verbose_name='任务类型')),
                ('stage_name', models.CharField(blank=True, default='', max_length=32, verbose_name='阶段名称')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='waiting', max_length=20, verbose_name='队列状态')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='任务参数')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_task_queues', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tasks', to='projects.project', verbose_name='分集项目')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_tasks', to='projects.series', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '分集任务队列',
                'verbose_name_plural': '分集任务队列',
                'db_table': 'episode_task_queue',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='episodetaskqueue',
            index=models.Index(fields=['series', 'status', 'created_at'], name='episode_tas_series__18f8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='episodetaskqueue',
            index=models.Index(fields=['project', 'status', 'created_at'], name='episode_tas_project_7152ad_idx'),
        ),
        migrations.AddIndex(
            model_name='episodetaskqueue',
            index=models.Index(fields=['celery_task_id'], name='episode_tas_celery__c73a3a_idx'),
        ),
    ]
