# Generated by Django 3.2.15 on 2026-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_project_asset_binding_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='stage_type',
            field=models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型'),
        ),
    ]
