# Generated by Django 3.2.15

from django.db import migrations
import uuid


def create_mock_providers(apps, schema_editor):
    """
    创建 Mock API 提供商配置
    用于测试和开发环境
    """
    ModelProvider = apps.get_model('models', 'ModelProvider')

    # Mock LLM 提供商
    mock_llm, created = ModelProvider.objects.get_or_create(
        name='Mock LLM API',
        defaults={
            'id': uuid.uuid4(),
            'provider_type': 'llm',
            'executor_class': 'core.ai_client.mock_llm_client.MockLLMClient',
            'api_url': 'http://localhost:8010/api/mock/llm/',
            'api_key': 'mock-api-key-not-required',
            'model_name': 'mock-llm-v1',
            'max_tokens': 4096,
            'temperature': 0.7,
            'top_p': 1.0,
            'timeout': 30,
            'is_active': True,
            'priority': 100,  # 高优先级，方便测试
            'rate_limit_rpm': 1000,
            'rate_limit_rpd': 100000,
            'extra_config': {
                'description': 'Mock LLM API，用于测试文案改写、分镜生成、运镜生成',
                'is_mock': True
            }
        }
    )
    if created:
        print(f"✓ 已创建 Mock LLM 提供商: {mock_llm.name}")

    # Mock 文生图提供商
    mock_text2image, created = ModelProvider.objects.get_or_create(
        name='Mock Text2Image API',
        defaults={
            'id': uuid.uuid4(),
            'provider_type': 'text2image',
            'executor_class': 'core.ai_client.mock_text2image_client.MockText2ImageClient',
            'api_url': 'http://localhost:8010/api/mock',
            'api_key': 'mock-api-key-not-required',
            'model_name': 'mock-text2image-v1',
            'timeout': 60,
            'is_active': True,
            'priority': 100,
            'rate_limit_rpm': 500,
            'rate_limit_rpd': 50000,
            'extra_config': {
                'description': 'Mock 文生图 API，返回占位图片用于测试',
                'is_mock': True,
                'default_ratio': '1:1',
                'default_resolution': '2k'
            }
        }
    )
    if created:
        print(f"✓ 已创建 Mock 文生图提供商: {mock_text2image.name}")

    # Mock 图生视频提供商
    mock_image2video, created = ModelProvider.objects.get_or_create(
        name='Mock Image2Video API',
        defaults={
            'id': uuid.uuid4(),
            'provider_type': 'image2video',
            'executor_class': 'core.ai_client.mock_image2video_client.MockImage2VideoClient',
            'api_url': 'http://localhost:8010/api/mock',
            'api_key': 'mock-api-key-not-required',
            'model_name': 'mock-image2video-v1',
            'timeout': 120,
            'is_active': True,
            'priority': 100,
            'rate_limit_rpm': 100,
            'rate_limit_rpd': 10000,
            'extra_config': {
                'description': 'Mock 图生视频 API，返回示例视频用于测试',
                'is_mock': True,
                'default_duration': 3.0,
                'default_fps': 24
            }
        }
    )
    if created:
        print(f"✓ 已创建 Mock 图生视频提供商: {mock_image2video.name}")

    print("\n✓ Mock API 提供商配置完成！")
    print("  - Mock LLM API: 用于文案改写、分镜生成、运镜生成")
    print("  - Mock Text2Image API: 用于文生图测试")
    print("  - Mock Image2Video API: 用于图生视频测试")


def remove_mock_providers(apps, schema_editor):
    """
    回滚操作：删除 Mock API 提供商
    """
    ModelProvider = apps.get_model('models', 'ModelProvider')

    deleted_count = ModelProvider.objects.filter(
        name__in=[
            'Mock LLM API',
            'Mock Text2Image API',
            'Mock Image2Video API'
        ]
    ).delete()[0]

    print(f"✓ 已删除 {deleted_count} 个 Mock API 提供商")


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_set_default_executors'),
    ]

    operations = [
        migrations.RunPython(create_mock_providers, remove_mock_providers),
    ]
