# Generated by Django 3.2.15 on 2026-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_update_image2video_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprovider',
            name='provider_type',
            field=models.CharField(choices=[('llm', 'LLM模型'), ('text2image', '文生图模型'), ('image2video', '图生视频模型'), ('image_edit', '图片编辑模型')], max_length=20, verbose_name='模型作用分类'),
        ),
    ]
