# Generated by Django 3.2.15 on 2026-01-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_set_default_executors'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramovement',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='生成元数据'),
        ),
        migrations.AddField(
            model_name='cameramovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='contentrewrite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='生成元数据'),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='model_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型'),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='prompt_used',
            field=models.TextField(blank=True, default='', verbose_name='使用的提示词'),
        ),
        migrations.AlterField(
            model_name='cameramovement',
            name='model_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型'),
        ),
        migrations.AlterField(
            model_name='cameramovement',
            name='movement_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='运镜参数'),
        ),
        migrations.AlterField(
            model_name='cameramovement',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('static', '静态'), ('zoom_in', '推进'), ('zoom_out', '拉远'), ('pan_left', '左移'), ('pan_right', '右移'), ('tilt_up', '上摇'), ('tilt_down', '下摇'), ('dolly_in', '前推'), ('dolly_out', '后拉')], default='', max_length=50, verbose_name='运镜类型'),
        ),
        migrations.AlterField(
            model_name='cameramovement',
            name='prompt_used',
            field=models.TextField(blank=True, default='', verbose_name='使用的提示词'),
        ),
        migrations.AlterField(
            model_name='contentrewrite',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='生成元数据'),
        ),
        migrations.AlterField(
            model_name='contentrewrite',
            name='prompt_used',
            field=models.TextField(blank=True, default='', verbose_name='使用的提示词'),
        ),
    ]
