# Generated by Django 3.2.15 on 2026-01-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20260116_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrewrite',
            name='rewritten_text',
            field=models.TextField(blank=True, default='', verbose_name='改写后文本'),
        ),
    ]
