# Generated by Django 3.2.15 on 2026-03-16 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_modelprovider_provider_type'),
        ('content', '0003_alter_contentrewrite_rewritten_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiGridImageTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_image_url', models.URLField(max_length=1024, verbose_name='多宫格原图URL')),
                ('grid_rows', models.IntegerField(default=2, verbose_name='行数')),
                ('grid_cols', models.IntegerField(default=2, verbose_name='列数')),
                ('tile_gap', models.IntegerField(default=0, verbose_name='格子间距')),
                ('outer_padding', models.IntegerField(default=0, verbose_name='外边距')),
                ('split_config', models.JSONField(blank=True, default=dict, verbose_name='切图配置')),
                ('generation_params', models.JSONField(blank=True, default=dict, verbose_name='生成参数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('prompt_used', models.TextField(blank=True, default='', verbose_name='使用的提示词')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, verbose_name='生成元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_grid_tasks', to='content.storyboard', verbose_name='分镜')),
            ],
            options={
                'verbose_name': '多宫格图片任务',
                'verbose_name_plural': '多宫格图片任务',
                'db_table': 'multi_grid_image_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiGridTile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tile_index', models.IntegerField(verbose_name='切片序号')),
                ('row_index', models.IntegerField(verbose_name='行序号')),
                ('col_index', models.IntegerField(verbose_name='列序号')),
                ('crop_box', models.JSONField(blank=True, default=dict, verbose_name='裁切区域')),
                ('tile_image_url', models.URLField(max_length=1024, verbose_name='切片图片URL')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='状态')),
                ('width', models.IntegerField(default=0, verbose_name='宽度')),
                ('height', models.IntegerField(default=0, verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='content.multigridimagetask', verbose_name='多宫格任务')),
            ],
            options={
                'verbose_name': '多宫格切片',
                'verbose_name_plural': '多宫格切片',
                'db_table': 'multi_grid_tiles',
                'ordering': ['tile_index'],
            },
        ),
        migrations.AddIndex(
            model_name='multigridtile',
            index=models.Index(fields=['task', 'tile_index'], name='multi_grid__task_id_2ed938_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='multigridtile',
            unique_together={('task', 'tile_index')},
        ),
        migrations.AddIndex(
            model_name='multigridimagetask',
            index=models.Index(fields=['storyboard', 'status'], name='multi_grid__storybo_ab6ae6_idx'),
        ),
    ]
