
# Generated by Django 3.2.15 on 2026-03-16 18:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20260316_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_stage_type', models.CharField(choices=[('image_generation', '文生图'), ('multi_grid_image', '多宫格图片')], default='multi_grid_image', max_length=20, verbose_name='来源阶段')),
                ('source_image_url', models.URLField(max_length=1024, verbose_name='源图片URL')),
                ('edited_image_url', models.URLField(max_length=1024, verbose_name='编辑后图片URL')),
                ('prompt_used', models.TextField(blank=True, default='', verbose_name='使用的提示词')),
                ('generation_params', models.JSONField(blank=True, default=dict, verbose_name='生成参数')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, verbose_name='生成元数据')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('width', models.IntegerField(default=0, verbose_name='宽度')),
                ('height', models.IntegerField(default=0, verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型')),
                ('multi_grid_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_images', to='content.multigridimagetask', verbose_name='来源多宫格任务')),
                ('multi_grid_tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_images', to='content.multigridtile', verbose_name='来源多宫格切片')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_images', to='content.storyboard', verbose_name='分镜')),
            ],
            options={
                'verbose_name': '图片编辑结果',
                'verbose_name_plural': '图片编辑结果',
                'db_table': 'edited_images',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='editedimage',
            index=models.Index(fields=['storyboard', 'status'], name='edited_imag_storybo_440fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='editedimage',
            index=models.Index(fields=['multi_grid_tile'], name='edited_imag_multi_g_9429af_idx'),
        ),
    ]
