# Generated by Django 3.2.15 on 2026-03-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_editedimage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='editedimage',
            name='edited_imag_storybo_440fbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='editedimage',
            name='edited_imag_multi_g_9429af_idx',
        ),
        migrations.AddIndex(
            model_name='editedimage',
            index=models.Index(fields=['storyboard', 'status'], name='edited_imag_storybo_8de7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='editedimage',
            index=models.Index(fields=['multi_grid_tile'], name='edited_imag_multi_g_016183_idx'),
        ),
    ]
