# Generated by Django 3.2.15 on 2025-12-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0002_prompttemplate_model_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, verbose_name='变量键')),
                ('value', models.TextField(verbose_name='变量值')),
                ('variable_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔值'), ('json', 'JSON对象')], default='string', max_length=20, verbose_name='变量类型')),
                ('scope', models.CharField(choices=[('system', '系统级'), ('user', '用户级')], default='user', max_length=20, verbose_name='作用域')),
                ('group', models.CharField(blank=True, default='', max_length=100, verbose_name='分组')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_variables', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '全局变量',
                'verbose_name_plural': '全局变量',
                'db_table': 'global_variables',
                'ordering': ['group', 'key'],
                'unique_together': {('key', 'created_by', 'scope')},
            },
        ),
        migrations.AddIndex(
            model_name='globalvariable',
            index=models.Index(fields=['scope', 'is_active'], name='global_vari_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='globalvariable',
            index=models.Index(fields=['created_by', 'is_active'], name='global_vari_created_idx'),
        ),
        migrations.AddIndex(
            model_name='globalvariable',
            index=models.Index(fields=['group', 'is_active'], name='global_vari_group_idx'),
        ),
    ]
