# Generated by Django 3.2.15 on 2025-12-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_globalvariable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='globalvariable',
            name='global_vari_scope_idx',
        ),
        migrations.RemoveIndex(
            model_name='globalvariable',
            name='global_vari_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='globalvariable',
            name='global_vari_group_idx',
        ),
        migrations.AddIndex(
            model_name='globalvariable',
            index=models.Index(fields=['scope', 'is_active'], name='global_vari_scope_c0f1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='globalvariable',
            index=models.Index(fields=['created_by', 'is_active'], name='global_vari_created_b0dddf_idx'),
        ),
        migrations.AddIndex(
            model_name='globalvariable',
            index=models.Index(fields=['group', 'is_active'], name='global_vari_group_16ddb9_idx'),
        ),
    ]
