# Generated by Django 3.2.15

from django.db import migrations
import uuid


def create_mock_prompt_template_set(apps, schema_editor):
    """
    创建 Mock API 的提示词模板集
    包含所有阶段的简化提示词模板
    """
    PromptTemplateSet = apps.get_model('prompts', 'PromptTemplateSet')
    PromptTemplate = apps.get_model('prompts', 'PromptTemplate')
    ModelProvider = apps.get_model('models', 'ModelProvider')
    User = apps.get_model('auth', 'User')

    # 获取或创建系统用户
    system_user, _ = User.objects.get_or_create(
        username='system',
        defaults={
            'email': 'system@example.com',
            'is_staff': True,
            'is_superuser': False
        }
    )

    # 获取 Mock 模型提供商
    try:
        mock_llm = ModelProvider.objects.get(name='Mock LLM API')
        mock_text2image = ModelProvider.objects.get(name='Mock Text2Image API')
        mock_image2video = ModelProvider.objects.get(name='Mock Image2Video API')
    except ModelProvider.DoesNotExist:
        print("⚠ 警告: Mock API 提供商不存在，请先运行 models app 的迁移")
        return

    # 创建提示词集
    template_set, created = PromptTemplateSet.objects.get_or_create(
        name='Mock API 测试模板集',
        defaults={
            'id': uuid.uuid4(),
            'description': 'Mock API 专用的简化提示词模板，用于快速测试工作流',
            'is_active': True,
            'is_default': False,
            'created_by': system_user
        }
    )

    if not created:
        print(f"✓ 提示词集已存在: {template_set.name}")
        return

    print(f"✓ 已创建提示词集: {template_set.name}")

    # 创建各阶段的提示词模板
    templates = [
        {
            'stage_type': 'rewrite',
            'model_provider': mock_llm,
            'template_content': '''请对以下内容进行改写和优化：

原始内容：
{{ original_content }}

要求：
1. 保持原意，使语言更加生动流畅
2. 适合用于视频脚本
3. 字数控制在 {{ max_length|default(500) }} 字以内

请直接输出改写后的内容。''',
            'variables': {
                'original_content': {'type': 'string', 'required': True, 'description': '原始内容'},
                'max_length': {'type': 'int', 'required': False, 'default': 500, 'description': '最大字数'}
            }
        },
        {
            'stage_type': 'storyboard',
            'model_provider': mock_llm,
            'template_content': '''请根据以下内容生成分镜脚本：

内容：
{{ rewritten_content }}

要求：
1. 生成 {{ scene_count|default(3) }} 个场景
2. 每个场景包含：场景描述、旁白文字、图片提示词、时长、运镜方式
3. 以 JSON 数组格式输出

输出格式示例：
[
  {
    "scene_number": 1,
    "scene_description": "场景描述",
    "narration_text": "旁白文字",
    "image_prompt": "英文图片提示词",
    "duration_seconds": 3,
    "camera_movement": "static"
  }
]

请直接输出 JSON 数组。''',
            'variables': {
                'rewritten_content': {'type': 'string', 'required': True, 'description': '改写后的内容'},
                'scene_count': {'type': 'int', 'required': False, 'default': 3, 'description': '场景数量'}
            }
        },
        {
            'stage_type': 'image_generation',
            'model_provider': mock_text2image,
            'template_content': '''{{ image_prompt }}''',
            'variables': {
                'image_prompt': {'type': 'string', 'required': True, 'description': '图片生成提示词'}
            }
        },
        {
            'stage_type': 'camera_movement',
            'model_provider': mock_llm,
            'template_content': '''请为以下场景生成运镜参数：

场景描述：
{{ scene_description }}

可用运镜类型：
- static: 静态镜头
- zoom_in: 推进
- zoom_out: 拉远
- pan_left: 左摇
- pan_right: 右摇
- tilt_up: 上摇
- tilt_down: 下摇
- follow: 跟随

要求：
以 JSON 格式输出运镜参数

输出格式示例：
{
  "movement_type": "slow_zoom_in",
  "movement_params": {
    "start_scale": 1.0,
    "end_scale": 1.2,
    "duration": 3.0,
    "easing": "ease_in_out"
  },
  "description": "缓慢推进镜头"
}

请直接输出 JSON 对象。''',
            'variables': {
                'scene_description': {'type': 'string', 'required': True, 'description': '场景描述'}
            }
        },
        {
            'stage_type': 'video_generation',
            'model_provider': mock_image2video,
            'template_content': '''根据图片和运镜参数生成视频

图片URL: {{ image_url }}
运镜参数: {{ camera_movement }}
时长: {{ duration|default(3.0) }} 秒
帧率: {{ fps|default(24) }} fps''',
            'variables': {
                'image_url': {'type': 'string', 'required': True, 'description': '源图片URL'},
                'camera_movement': {'type': 'json', 'required': True, 'description': '运镜参数'},
                'duration': {'type': 'float', 'required': False, 'default': 3.0, 'description': '视频时长'},
                'fps': {'type': 'int', 'required': False, 'default': 24, 'description': '帧率'}
            }
        }
    ]

    # 创建模板
    stage_names = {
        'rewrite': '文案改写',
        'storyboard': '分镜生成',
        'image_generation': '文生图',
        'camera_movement': '运镜生成',
        'video_generation': '图生视频'
    }

    for template_data in templates:
        template, created = PromptTemplate.objects.get_or_create(
            template_set=template_set,
            stage_type=template_data['stage_type'],
            defaults={
                'id': uuid.uuid4(),
                'model_provider': template_data['model_provider'],
                'template_content': template_data['template_content'],
                'variables': template_data['variables'],
                'version': 1,
                'is_active': True
            }
        )
        if created:
            stage_name = stage_names.get(template_data['stage_type'])
            print(f"  ✓ 已创建模板: {stage_name}")

    print("\n✓ Mock API 提示词模板集创建完成！")
    print("  包含 5 个阶段的模板：")
    print("  - 文案改写 (rewrite)")
    print("  - 分镜生成 (storyboard)")
    print("  - 文生图 (image_generation)")
    print("  - 运镜生成 (camera_movement)")
    print("  - 图生视频 (video_generation)")


def remove_mock_prompt_template_set(apps, schema_editor):
    """
    回滚操作：删除 Mock API 提示词模板集
    """
    PromptTemplateSet = apps.get_model('prompts', 'PromptTemplateSet')

    deleted_count = PromptTemplateSet.objects.filter(
        name='Mock API 测试模板集'
    ).delete()[0]

    print(f"✓ 已删除 Mock API 提示词模板集（共 {deleted_count} 条记录）")


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_auto_20251215_1049'),
        ('models', '0004_create_mock_providers'),  # 依赖 Mock 提供商
    ]

    operations = [
        migrations.RunPython(
            create_mock_prompt_template_set,
            remove_mock_prompt_template_set
        ),
    ]
