# Generated by Django 3.2.15 on 2026-01-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_create_mock_prompt_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalvariable',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/%Y/%m/', verbose_name='图片文件'),
        ),
        migrations.AlterField(
            model_name='globalvariable',
            name='value',
            field=models.TextField(blank=True, default='', verbose_name='变量值'),
        ),
        migrations.AlterField(
            model_name='globalvariable',
            name='variable_type',
            field=models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔值'), ('json', 'JSON对象'), ('image', '图片')], default='string', max_length=20, verbose_name='变量类型'),
        ),
    ]
