# Generated by Codex

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_create_mock_providers'),
        ('prompts', '0006_add_image_type_to_globalvariable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptDebugSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='会话名称')),
                ('stage_type', models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频')], max_length=20, verbose_name='阶段类型')),
                ('draft_template_content', models.TextField(blank=True, default='', verbose_name='草稿模板内容')),
                ('draft_variables', models.JSONField(blank=True, default=dict, verbose_name='草稿变量定义')),
                ('latest_variable_values', models.JSONField(blank=True, default=dict, verbose_name='最近变量值')),
                ('latest_input_payload', models.JSONField(blank=True, default=dict, verbose_name='最近输入载荷')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近运行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_debug_sessions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_debug_sessions', to='models.modelprovider', verbose_name='调试模型')),
                ('prompt_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_sessions', to='prompts.prompttemplate', verbose_name='提示词模板')),
                ('template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_sessions', to='prompts.prompttemplateset', verbose_name='提示词集')),
            ],
            options={
                'verbose_name': '提示词调试会话',
                'verbose_name_plural': '提示词调试会话',
                'db_table': 'prompt_debug_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptDebugRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频')], max_length=20, verbose_name='阶段类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('template_snapshot', models.TextField(blank=True, default='', verbose_name='模板快照')),
                ('variable_values', models.JSONField(blank=True, default=dict, verbose_name='变量值')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='输入载荷')),
                ('resolved_variables', models.JSONField(blank=True, default=dict, verbose_name='解析后变量')),
                ('rendered_prompt', models.TextField(blank=True, default='', verbose_name='渲染后提示词')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='原始响应')),
                ('parsed_output', models.JSONField(blank=True, default=dict, verbose_name='解析后输出')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='延迟(毫秒)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_debug_runs', to='models.modelprovider', verbose_name='使用模型')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='prompts.promptdebugsession', verbose_name='调试会话')),
            ],
            options={
                'verbose_name': '提示词调试运行',
                'verbose_name_plural': '提示词调试运行',
                'db_table': 'prompt_debug_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptDebugArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('text', '文本'), ('storyboard_bundle', '分镜集合'), ('storyboard_item', '分镜条目'), ('image', '图片'), ('video', '视频')], max_length=30, verbose_name='资产类型')),
                ('stage_type', models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频')], max_length=20, verbose_name='阶段类型')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('sequence_number', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='资产内容')),
                ('preview_text', models.TextField(blank=True, default='', verbose_name='预览文本')),
                ('preview_image_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='预览图片')),
                ('preview_video_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='预览视频')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否固定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_debug_artifacts', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='prompts.promptdebugrun', verbose_name='调试运行')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='prompts.promptdebugartifact', verbose_name='来源资产')),
            ],
            options={
                'verbose_name': '提示词调试资产',
                'verbose_name_plural': '提示词调试资产',
                'db_table': 'prompt_debug_artifacts',
                'ordering': ['stage_type', 'sequence_number', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='promptdebugsession',
            name='latest_source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_sessions', to='prompts.promptdebugartifact', verbose_name='最近引用资产'),
        ),
        migrations.AddField(
            model_name='promptdebugrun',
            name='source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_runs', to='prompts.promptdebugartifact', verbose_name='来源资产'),
        ),
        migrations.AddIndex(
            model_name='promptdebugsession',
            index=models.Index(fields=['created_by', 'stage_type'], name='prompt_debu_created_6dbbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugsession',
            index=models.Index(fields=['prompt_template', '-updated_at'], name='prompt_debu_prompt__a93530_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugrun',
            index=models.Index(fields=['session', '-created_at'], name='prompt_debu_session_f76700_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugrun',
            index=models.Index(fields=['stage_type', 'status'], name='prompt_debu_stage_t_a87dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugartifact',
            index=models.Index(fields=['created_by', 'artifact_type'], name='prompt_debu_created_ef2d52_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugartifact',
            index=models.Index(fields=['stage_type', 'artifact_type'], name='prompt_debu_stage_t_fb76a8_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugartifact',
            index=models.Index(fields=['run', 'sequence_number'], name='prompt_debu_run_id_a41fb2_idx'),
        ),
    ]
