# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0007_prompt_debug_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prompttemplate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_active=True),
                fields=('template_set', 'stage_type'),
                name='uniq_active_template_per_stage',
            ),
        ),
    ]
