# Generated by Django 3.2.15 on 2026-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0008_prompt_template_active_unique'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promptdebugartifact',
            name='prompt_debu_created_ef2d52_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptdebugartifact',
            name='prompt_debu_stage_t_fb76a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptdebugartifact',
            name='prompt_debu_run_id_a41fb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptdebugrun',
            name='prompt_debu_session_f76700_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptdebugrun',
            name='prompt_debu_stage_t_a87dd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptdebugsession',
            name='prompt_debu_created_6dbbc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptdebugsession',
            name='prompt_debu_prompt__a93530_idx',
        ),
        migrations.AlterField(
            model_name='promptdebugartifact',
            name='stage_type',
            field=models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型'),
        ),
        migrations.AlterField(
            model_name='promptdebugrun',
            name='stage_type',
            field=models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型'),
        ),
        migrations.AlterField(
            model_name='promptdebugsession',
            name='stage_type',
            field=models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='stage_type',
            field=models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型'),
        ),
        migrations.AddIndex(
            model_name='promptdebugartifact',
            index=models.Index(fields=['created_by', 'artifact_type'], name='prompt_debu_created_d6ec04_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugartifact',
            index=models.Index(fields=['stage_type', 'artifact_type'], name='prompt_debu_stage_t_0930da_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugartifact',
            index=models.Index(fields=['run', 'sequence_number'], name='prompt_debu_run_id_0f2ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugrun',
            index=models.Index(fields=['session', '-created_at'], name='prompt_debu_session_16e4df_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugrun',
            index=models.Index(fields=['stage_type', 'status'], name='prompt_debu_stage_t_127360_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugsession',
            index=models.Index(fields=['created_by', 'stage_type'], name='prompt_debu_created_c2b948_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugsession',
            index=models.Index(fields=['prompt_template', '-updated_at'], name='prompt_debu_prompt__04ef1f_idx'),
        ),
    ]
